app = "biodiversity-dashboard"
primary_region = "fra"

[build]

[env]
  API_HOST = "0.0.0.0"
  API_PORT = "8080"
  CORS_ORIGINS = "https://biodiversity-dashboard.fly.dev"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[http_service.checks]]
  grace_period = "10s"
  interval = "30s"
  method = "GET"
  timeout = "5s"
  path = "/health"
